### ISSUE TITLE
not showing in order admin page on presta 1.7.7.0

### ISSUE THREAD

**Issue by bluegifts** [sameday-courier/prestashop-plugin#23]
Hello.
After updating to 1.7.7.0 module does not shows in order page, even it,s hooked to appear.

**Comment by rbulat76** [comment]
Same problem here

**Comment by javicisro** [comment]
It is a hooks problem. New order page full revamp and migrate to symphony.

https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/

See screenshot.

![new-presta-1-7-7-0-hooks](https://user-images.githubusercontent.com/7247785/102483537-9035f400-406d-11eb-9a33-6e7b0b8208d5.png)

**Comment by bluegifts** [comment]
> It is a hooks problem. New order page full revamp and migrate to symphony.
> 
> https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/
> 
> See screenshot.
> 
> ![new-presta-1-7-7-0-hooks](https://user-images.githubusercontent.com/7247785/102483537-9035f400-406d-11eb-9a33-6e7b0b8208d5.png)

We know that, we are waiting for a solution :)

**Comment by javicisro** [comment]
Removed hook	

displayAdminOrderContentOrder

and

displayAdminOrderContentShip

New hook

displayAdminOrderTabContent

Both hooks are now combined in a single generic hook that allows you to include tab contents the order view page, it only has the id_order as a parameter

**Comment by javicisro** [comment]
In folder modules > samedaycourier open "samedaycourier.php" search for "displayAdminOrderContentShip" and replace with "displayAdminOrderTabContent".

Remember to do a backup before. Also this is the fix just for > presta 1.7.7.0 (new back-office order page).

Also I would rename the "Add AWB" button to "Add Sameday AWB" in views\templates\hook\"displayAdminOrder.tpl"

See screenshots.

You can download full new sameday module archive fixed for presta 1.7.7.0 from here: https://prodtp.ro/samedaycourier.zip

You're welcome!

![add-awb-vs-add-sameday-awb](https://user-images.githubusercontent.com/7247785/102492481-6cc57600-407a-11eb-818e-0f6e1dedc3e6.png)
![displayAdminOrderTabContent-vs-displayAdminOrderContentShip](https://user-images.githubusercontent.com/7247785/102492483-6d5e0c80-407a-11eb-8b6d-54ee68728da6.png)
![modules-prestashop](https://user-images.githubusercontent.com/7247785/102492486-6d5e0c80-407a-11eb-8b3c-2a7cb5cff230.png)
![sameday-order-page-ps-1-7-7-0](https://user-images.githubusercontent.com/7247785/102492488-6df6a300-407a-11eb-9b5a-d989b21d5e4c.png)

**Comment by bluegifts** [comment]
Added , button showed up, pop-up when click on button but after click generate nothing happen, only th pop-up dissapear. No awb generated,

**Comment by rbulat76** [comment]
same situation here

**Comment by javicisro** [comment]
@rbulat76 @bluegifts back to the drawing board, my bad...

**Comment by rbulat76** [comment]
ok. thanks a lot. we owe you:)

**Comment by bluegifts** [comment]
> same situation here

did you manage to install new module 1.4.2? it.s working?
for me did not work, pop-up appears but after click generate nothing happened, only pop-up dissapear.

**Comment by rbulat76** [comment]
No. it doesn't work

**Comment by javicisro** [comment]
@bluegifts and @rbulat76 uninstall / delete previous version and reinstall so it will enable the proper hooks (overrides); it „works“ but needs some display problems adjusted,

**Comment by rbulat76** [comment]
the module is not available here:
https://prodtp.ro/samedaycourier.zip

**Comment by javicisro** [comment]
@rbulat76 use latest release from github made yesterday by @Soptareanu!

**Comment by rbulat76** [comment]
same situation (with module of @Soptareanu ). 

when generating the AWB nothing happens. AWB is not generated in the order BO screen and is not available also in https://eawb.sameday.ro

**Comment by javicisro** [comment]
@rbulat76 see attached screenshots (are you sure you installed the latest available release?). also keep in mind it is not fixed it is work in progress.
![sameday-5](https://user-images.githubusercontent.com/7247785/102981419-974b7f00-4511-11eb-8dcc-5cbc8361fe5f.png)
![sameday-4](https://user-images.githubusercontent.com/7247785/102981420-97e41580-4511-11eb-997a-baa303c68c1d.png)
![sameday-3](https://user-images.githubusercontent.com/7247785/102981422-97e41580-4511-11eb-985a-776bab4e9b14.png)
![sameday-2](https://user-images.githubusercontent.com/7247785/102981424-987cac00-4511-11eb-86fd-8211e29bd88b.png)
![sameday-1](https://user-images.githubusercontent.com/7247785/102981427-987cac00-4511-11eb-9e19-946e86211963.png)

**Comment by bluegifts** [comment]
> same situation (with module of @Soptareanu ).
> 
> when generating the AWB nothing happens. AWB is not generated in the order BO screen and is not available also in https://eawb.sameday.ro

hello
last version of module works with following issues:
- pdf generated is blank
- afte click generate you have to change manually status of order to shipped or exit and come back to order and you will see the awb no completed in transporters tab (if you click refresh the awb will be doubled).

**Comment by javicisro** [comment]
@bluegifts you can download (print) valid pdf awb from https://eawb.sameday.ro.

There is still stuff to fix.

**Comment by bluegifts** [comment]
> @bluegifts you can download (print) valid pdf awb from https://eawb.sameday.ro.
> 
> There is still stuff to fix.

yes, that.s right but still needed to be fixed

**Comment by rbulat76** [comment]
yes. now it works (with awb available in https://eawb.sameday.ro).

but for some reason had to make the changes in samedaycourier.php manually
