### ISSUE TITLE
Connection could not be established.

### ISSUE THREAD

**Issue by gabriel-negrea** [sameday-courier/prestashop-plugin#33]
Salut. Am instalat acest modul pe Prestashop 1.7.6.4., am introdus user si parola si zice Connection could not be established cand apas Test connection. Cand apas pe butonul mic cu Import services from sameday servers se deschide o pagina care arata urmatorul mesaj: "Oops! An Error Occurred The server returned a "500 Internal Server Error". Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."
Nu-mi dau seama daca problema e de la site-ul nostru sau de la sameday.
Aveti ceva sugestii ce-as putea face? 
Multumesc

**Comment by bluegifts** [comment]
Slutare. Problema este cel mai probabil de la voi, modulul este functional.

**Comment by gabriel-negrea** [comment]
Salut, Multumesc de raspuns. Intr-adevar, problema erau credentialele gresite despre care nu stiam, la momentul respectiv, ca fusesera schimbate.
