### ISSUE TITLE
Nu apare awb ul dupa il generez 1.7.7.8

### ISSUE THREAD

**Issue by luslucian** [sameday-courier/prestashop-plugin#39]
Salut, am facut upgrade la 1.7.7.8 generez awb ul apare in self awb dar in prestashp dupa ce il descarc zice ca e corupted.. nu il pot deschide
Atasat un filmulet … ce pot face ? 
https://share.icloud.com/photos/0feojEeJlePqsRewW6i950xEg

**Comment by Soptareanu** [comment]
We fix this issue. Please try to upgrade our plugin to the latest version.
