### ISSUE TITLE
erore la instalare : unexpected 'use' (T_USE)

### ISSUE THREAD

**Issue by dandumit** [sameday-courier/prestashop-plugin#6]
Buna,
Asteptam de mult acest modul. L-am instalat insa imi da eroarea de mai jos :

[PrestaShop] Fatal error in module file :/home/dandumit/public_html/magtest/classes/module/Module.php(1361) : eval()'d code:
syntax error, unexpected 'use' (T_USE)

Multumesc,
Daniel

**Comment by dandumit** [comment]
Am comentat liniile cu use . folderul trebuie sa se numeasca ca si numele clasei samedaycourier,

**Comment by danut007ro** [comment]
Salutare,

Am facut update la documentatie. Suntem de asemenea in procedura de publicare pe marketplace.
