### ISSUE TITLE
Locker Option without selection

### ISSUE THREAD

**Issue by theeldermaster** [sameday-courier/prestashop-plugin#74]
Hello,
In current version if the client selection in front office is the Locker Option, but he is not selecting effectively any locker, the system still allow to go further and complete the order.
In conclusion when the admin will try to generate the AWB, will get a BIG error of course because no ID of locker exists.
If in any human logic a client should select a locker before continuing further, the system should force the user to select a locker before allowing him to go further. We had this kind of case and the client replied to us that he was not paying attention that he was selecting Locker word because was in a hurry and he selected only Sameday. So this case can occur and should be fixed. To force the client to select a locker before continue.
In same time the ADMIN should see in order details the locker name /ID
Best regards,
![CaptureSamedayLocker](https://user-images.githubusercontent.com/79221101/191254846-e143b0e5-0107-427b-8cb6-fa0383495b93.PNG)

**Comment by salbatyku** [comment]
You can add required to the select field. (that would solve it temporarily).

**Comment by theeldermaster** [comment]
In last versions of the module this issue wax fixed. It works as it is required.
