### ISSUE TITLE
Acest fisier nu pare a fi o arhiva zip valida de modul

### ISSUE THREAD

**Issue by m3nt0l** [sameday-courier/prestashop-plugin#8]
Primesc aceasta eroare atunci cand incerc sa-l istalez.

Am incercat pe versiunile 1.7.1.2 si 1.7.5.2 

Cum pot rezolva? Trebuie sa am o versiune si mai mica de prestashop decat 1.7.1.2?

**Comment by danut007ro** [comment]
Arhiva descărcată de pe GitHub conține release-ul efectiv, nu și folderul samedaycourier.

Conținutul arhivei trebuie extras într-un folder nou numit modules/samedaycourier
