### ISSUE TITLE
butonul Edit din comanda / Tracking number ... nu mai functioneaza in v1.4.30 

### ISSUE THREAD

**Issue by rrusu** [sameday-courier/prestashop-plugin#87]
Buna,
Presta Shop 1.6.1.24
Sameday Courier v1.4.30 - de Sameday Courier

Folosim in mod current 3 curieri.
Fiecare are setat la Shipping -> Carriers -> Editeaza Curier -> Tracking URL de forma: [http://example.com/track.php?num=@' with '@' where the tracking number should appear.](http://example.com/track.php?num=@%27%20with%20%27@%27%20where%20the%20tracking%20number%20should%20appear.) … asa cum zice PS-ul.
Fiecare client cand face comanda alege curierul dupa preferintele acestuia.
In comanda la Shipping apare si Tracking number. In dreapta este butonul “Edit” unde se scrie numarul AWB-ului.
Dupa ce apesi Edit si adaugi numarul de AWB, PS-ul trimite catre client un email & link de forma celui de sus iar mai departe clientul poate sa urmareasca pe pagina curierului unde este coletul.

Am facut saptama asta undate de la Sameday Courier v1.4.25 la v1.4.30 … butonul Edit nu mai functioneaza.
Va rog investigati si dvs. … folosim optiunea respectiva din PS si avem nevoie sa functioneze iar.
Multumesc anticipat.
Liviu.
![Edit - Tracking number](https://user-images.githubusercontent.com/8981740/212380580-2c91a216-ab7a-4e86-9973-1b405b227c8d.JPG)

**Comment by Soptareanu** [comment]
> Buna, Presta Shop 1.6.1.24 Sameday Courier v1.4.30 - de Sameday Courier
> 
> Folosim in mod current 3 curieri. Fiecare are setat la Shipping -> Carriers -> Editeaza Curier -> Tracking URL de forma: [http://example.com/track.php?num=@' with '@' where the tracking number should appear.](http://example.com/track.php?num=@%27%20with%20%27@%27%20where%20the%20tracking%20number%20should%20appear.) … asa cum zice PS-ul. Fiecare client cand face comanda alege curierul dupa preferintele acestuia. In comanda la Shipping apare si Tracking number. In dreapta este butonul “Edit” unde se scrie numarul AWB-ului. Dupa ce apesi Edit si adaugi numarul de AWB, PS-ul trimite catre client un email & link de forma celui de sus iar mai departe clientul poate sa urmareasca pe pagina curierului unde este coletul.
> 
> Am facut saptama asta undate de la Sameday Courier v1.4.25 la v1.4.30 … butonul Edit nu mai functioneaza. Va rog investigati si dvs. … folosim optiunea respectiva din PS si avem nevoie sa functioneze iar. Multumesc anticipat. Liviu. ![Edit - Tracking number](https://user-images.githubusercontent.com/8981740/212380580-2c91a216-ab7a-4e86-9973-1b405b227c8d.JPG)

Vom investiga si noi si revenim cat mai urgent posibil cu un raspuns.

**Comment by rrusu** [comment]
Salutare. Am facut modificarea. Este ok acum. Multumesc.
