### ISSUE TITLE
Uncaught Symfony\Component\Debug\Exception\FatalThrowableError

### ISSUE THREAD

**Issue by m3nt0l** [sameday-courier/prestashop-plugin#9]
Prestashop 1.7.5.1 
Primesc aceasta eroare cand adaug user-ul si parola si apas "Testeaza conexiunea".

Cum pot rezolva?

Multumesc

[PrestaShop] Fatal error in module file: /home3/r69676vogu/public_html/app/bootstrap.php.cache:3225
Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getLockers() on null in /home3/r69676vogu/public_html/modules/samedaycourier/samedaycourier.php:895 Stack trace: #0 /home3/r69676vogu/public_html/modules/samedaycourier/samedaycourier.php(789): SamedayCourier->importLockers() #1 /home3/r69676vogu/public_html/modules/samedaycourier/samedaycourier.php(139): SamedayCourier->postProcess() #2 /home3/r69676vogu/public_html/controllers/admin/AdminModulesController.php(907): SamedayCourier->getContent() #3 /home3/r69676vogu/public_html/controllers/admin/AdminModulesController.php(1166): AdminModulesControllerCore->postProcessCallback() #4 /home3/r69676vogu/public_html/classes/controller/Controller.php(194): AdminModulesControllerCore->postProcess() #5 /home3/r69676vogu/public_html/classes/Dispatcher.php(369): ControllerCore->run() #6 /home3/r69676vogu/public_html/admin376d8onir/index.php(95): DispatcherCore->dispatch() #7 {main} Next LogicException: Request stack is empty in /h

**Comment by danut007ro** [comment]
Salutare, am rezolvat problema. Din cauza unei probleme de comunicare (gen nu se poate conecta la server) codul se rula mai departe cu o instanta de obiect invalida.
